variables:
  build_env_reddit_port : "A global variable"
  build_env_ip : ""
image: ruby:2.4.5

stages:
  - build
  - test
  - review
  - stage
  - production
variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
- cd reddit
- bundle install
- apt-get update && apt-get install -y docker.io
- docker info

build_job:
  stage: build
  script:
    - echo 'Building'
    - docker build -t "reddit_$CI_ENVIRONMENT_SLUG":1.0 .
    - docker run --name "reddit_$CI_ENVIRONMENT_SLUG" -d -p 9292 "reddit_$CI_ENVIRONMENT_SLUG":1.0
    - $build_env_reddit_port=docker port "reddit_$CI_ENVIRONMENT_SLUG" 9292/tcp | head -1 | cut -d ':' -f 2
    - $build_env_ip=curl ipinfo.io/ip

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - echo 'Testing 1'
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: "http://$build_env_ip:$build_env_reddit_port"
  only:
    - branches
  except:
    - master
staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com
production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

