variables:
  build_env_reddit_port : ""
  build_env_ip : "http://127.0.0.1"
  DATABASE_URL: 'mongodb://mongo/user_posts'
  CI_REGISTRY_USER: 'coolf124'
  CI_REGISTRY_PASSWORD: 'qwerty124FF!'
  CI_REGISTRY : ""
stages:
  - build
  - test
  - review
  - stage
  - production

before_script:
  

build_job:
  image: docker:stable
  stage: build
  script:
    - echo 'Building'
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd reddit
    - docker pull $CI_REGISTRY_USER/reddit:latest  || true  
    - docker build  --cache-from $CI_REGISTRY_USER/reddit:latest -t $CI_REGISTRY_USER/reddit:gitlab-$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_USER/reddit:latest . 
    - docker run --name "reddit_gitlab_$CI_ENVIRONMENT_SLUG_$CI_COMMIT_SHORT_SHA" -d -p 9292 $CI_REGISTRY_USER/reddit:gitlab-$CI_COMMIT_SHORT_SHA
    - apk add curl
    - build_env_ip=$(curl ipinfo.io/ip)
    - echo "reddit_gitlab_$CI_ENVIRONMENT_SLUG_$CI_COMMIT_SHORT_SHA"
    - cut --help
    - head --help
    - sleep 7
    - build_env_reddit_port=$(docker port "reddit_gitlab_$CI_ENVIRONMENT_SLUG_$CI_COMMIT_SHORT_SHA" 9292/tcp | head -1 | cut -d ':' -f 2)
    - cd ..
    - touch build.env
    - echo "env_build_env_ip=$build_env_ip" >> build.env
    - echo "env_build_env_reddit_port=$build_env_reddit_port" >> build.env
    - echo "Finished build actions"
    - docker push $CI_REGISTRY_USER/reddit:gitlab-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_USER/reddit:latest 
  artifacts:
    reports:
      dotenv: build.env

test_unit_job:
  image: docker:stable
  stage: test
  script:
    - echo 'Testing 1'
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_USER/reddit:gitlab-$CI_COMMIT_SHORT_SHA
    - docker run --rm $CI_REGISTRY_USER/reddit:gitlab-$CI_COMMIT_SHORT_SHA /bin/sh -c "./start.sh& cd reddit && ruby simpletest.rb"
test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'
    
deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
branch review:
  stage: review
  script: 
    - echo "Deploy to $CI_ENVIRONMENT_SLUG"
    - echo "http://$env_build_env_ip:$env_build_env_reddit_port"
    - apk add curl
    - 'curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\": \"-852858068\", \"text\": \"CI: Для ветки $CI_COMMIT_REF_NAME загружен новый commit $CI_COMMIT_SHORT_SHA, посмотреть приложение:http://$env_build_env_ip:$env_build_env_reddit_port"}" https://api.telegram.org/bot5952209752:AAGGLizylcg8PTzAIXLsHE2OgzDiTTjLCcg/sendMessage'
  needs:
    - job: build_job
      artifacts: true
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$env_build_env_ip:$env_build_env_reddit_port
  only:
    - branches
  except:
    - master
staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: beta
    url: http://beta.example.com
production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com

