#added file to pass github actions test
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: nfs-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
